### ISSUE TITLE
Unable to find async functions

### ISSUE THREAD

**Issue by ip-sf** [davidenunes/mkgendocs#5]
Love the tool, using it for a few projects.

Ran into this today that is pretty straightforward, I would surmise that `async def func_name()` was not included in scope for the original development.

If i can provide more data or details, please let me know!

# Reproduction of Error
## main.py
```python
async def a_func() ->> bool:
    """ A Test Func
    
    Returns:
        bool: Returns True always
    """
    return True
```
## mkgendocs.yml
```yaml
---
sources_dir: docs
version: main

pages:
  - page: main.md
    source: main.py
    functions:
      - a_func
```
## GenDocs (Fail)
```bash
% gendocs --config mkgendocs.yml
>Loading configuration file
>Cleaning up existing sources directory.
>Populating sources directory with templates.
>Generating docs ...
>Building ref index...
>Generating docs for a_func
Traceback (most recent call last):
  File "/Users/user/git/project_repository/env/bin/gendocs", line 8, in <module>
    sys.exit(main())
  File "/Users/user/git/project_repository/env/lib/python3.10/site-packages/mkgendocs/gendocs.py", line 412, in main
    generate(args.config)
  File "/Users/user/git/project_repository/env/lib/python3.10/site-packages/mkgendocs/gendocs.py", line 379, in generate
    fn_info = extract.get_function(fn)
  File "/Users/user/git/project_repository/env/lib/python3.10/site-packages/mkgendocs/parse.py", line 637, in get_function
    fn = self._get_function(function_name)
  File "/Users/user/git/project_repository/env/lib/python3.10/site-packages/mkgendocs/parse.py", line 681, in _get_function
    raise Exception("function %s not found in %s" % (function_name, self.path))
Exception: function a_func not found in /Users/user/git/project_repository/main.py
```
## Modify main.py (remove async)
```python
def a_func() ->> bool:
    """ A Test Func
    
    Returns:
        bool: Returns True always
    """
    return True
```

## GenDocs (Succeed)
```bash
% gendocs --config mkgendocs.yml
>Loading configuration file
>Cleaning up existing sources directory.
>Populating sources directory with templates.
>Generating docs ...
>Building ref index...
>Generating docs for a_func
>Creating new page with autogenerated content:docs/main.md
```

**Comment by davidenunes** [comment]
you are correct, I did this very hastily for my own use at the time and forgot to consider async def
objects which are different types in python ast (Abstract Syntax Trees). There are similar issues with annotated methods/functions
that I intend to solve when I have time. 

for in the latest patch 0.9.1 I made it so that if finds the function object for async functions and returns the signature.


In the future I need to consider that users might want to mark these as async in the documentations
for now it's just a quick patch that should get you up and running, let me know if there's something fundamentally broken
about it

cheers

**Comment by ip-sf** [comment]
Thank you for your support and quick patch!
